# Namespace where the chart is deployed (separate from target namespaces)
namespace: aws-ecr-secret-updater

# AWS configuration
aws:
  # AWS region for ECR
  region: "us-east-1"
  # AWS account ID
  accountId: "123456789012"
  # AWS access key ID
  accessKeyId: ""
  # AWS secret access key
  secretAccessKey: ""

# Target namespaces to manage secrets in
namespaces:
  - default

# CronJob configuration
cronJob:
  # Run every 12 hours
  schedule: "0 */12 * * *"
  # TTL for the CronJob
  ttlSecondsAfterFinished: 600
  image:
    # GitHub Container Registry
    repository: "ghcr.io/christian-deleon/aws-ecr-secret-updater"
    # Default tag
    tag: "latest"

# Service account configuration
serviceAccount:
  # Create a new service account by default
  create: false
  # Name of the new service account
  name: "aws-ecr-secret-updater"
  # Patch default service accounts in target namespaces
  patchDefault: true

# Name of the secret to create/update
secretName: "aws-ecr-secret"
