{{- if and .Values.aws.accessKeyId .Values.aws.secretAccessKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-aws-credentials
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ $.Values.aws.accessKeyId | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ $.Values.aws.secretAccessKey | b64enc }}
{{- end }}