apiVersion: v1
kind: ConfigMap
metadata:
  name: update-ecr-secret
data:
  update-ecr-secret.sh: |
    #!/bin/sh -e

    REGION="{{ .Values.aws.region }}"
    REGISTRY="{{ .Values.aws.accountId }}.dkr.ecr.${REGION}.amazonaws.com"
    PASSWORD=$(aws ecr get-login-password --region $REGION)

    NAMESPACES=({{ join " " .Values.namespaces }})

    for ns in $NAMESPACES; do
      echo "Updating secret in namespace: $ns"

      # Create or update the secret
      kubectl create secret docker-registry $SECRET_NAME \
          --docker-server=$REGISTRY \
          --docker-username=AWS \
          --docker-password=$PASSWORD \
          --dry-run=client -o yaml | kubectl apply -f - -n $ns

      # Patch the default service account if enabled
      if [ "$PATCH_DEFAULT_SA" = "true" ]; then
          echo "Patching default service account in namespace: $ns"
          kubectl patch serviceaccount default -n $ns --type merge -p "{\"imagePullSecrets\": [{\"name\": \"$SECRET_NAME\"}]}"
      fi
    done
