apiVersion: batch/v1
kind: CronJob
metadata:
  name: aws-ecr-secret-updater
  namespace: {{ .Values.namespace }}
spec:
  schedule: {{ .Values.cronJob.schedule | quote }}
  ttlSecondsAfterFinished: {{ .Values.cronJob.ttlSecondsAfterFinished }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: aws-ecr-secret-updater
          restartPolicy: OnFailure
          containers:
            - name: aws-ecr-secret-updater
              image: {{ .Values.cronJob.image.repository }}:{{ .Values.cronJob.image.tag }}
              command: ["/bin/sh", "/app/update-ecr-secret.sh"]
              {{- if and .Values.aws.accessKeyId .Values.aws.secretAccessKey }}
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: aws-credentials
                      key: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: aws-credentials
                      key: AWS_SECRET_ACCESS_KEY
              {{- end }}
              volumeMounts:
                - name: update-ecr-secret
                  mountPath: /app/update-ecr-secret.sh
                  subPath: update-ecr-secret.sh
          volumes:
            - name: update-ecr-secret
              configMap:
                name: update-ecr-secret
                defaultMode: 0755
