apiVersion: batch/v1
kind: CronJob
metadata:
  name: aws-ecr-secret-updater
  namespace: {{ .Values.namespace }}
spec:
  schedule: {{ .Values.cronJob.schedule | quote }}
  ttlSecondsAfterFinished: {{ .Values.cronJob.ttlSecondsAfterFinished }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ if .Values.serviceAccount.create }}{{ .Values.serviceAccount.name }}{{ else }}default{{ end }}
          restartPolicy: OnFailure
          containers:
            - name: aws-ecr-secret-updater
              image: {{ .Values.cronJob.image.repository }}:{{ .Values.cronJob.image.tag }}
              command: ["/bin/sh", "/app/update-ecr-secret.sh"]
              env:
                - name: AWS_REGION
                  value: {{ .Values.aws.region | quote }}
                - name: AWS_ACCOUNT_ID
                  value: {{ .Values.aws.accountId | quote }}
                - name: NAMESPACES
                  value: {{ join " " .Values.namespaces | quote }}
                - name: SECRET_NAME
                  value: {{ .Values.secretName | quote }}
                - name: PATCH_DEFAULT_SA
                  value: {{ .Values.serviceAccount.patchDefault | quote }}
                {{- if and .Values.aws.accessKeyId .Values.aws.secretAccessKey }}
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: aws-credentials
                      key: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: aws-credentials
                      key: AWS_SECRET_ACCESS_KEY
                {{- end }}
