{{- range .Values.namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ecr-secret-manager
  namespace: {{ . }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "patch"]
{{- if $.Values.serviceAccount.patchDefault }}
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get", "patch"]
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ecr-secret-manager-binding
  namespace: {{ . }}
subjects:
  - kind: ServiceAccount
    name: {{ if $.Values.serviceAccount.create }}{{ $.Values.serviceAccount.name }}{{ else }}default{{ end }}
    namespace: {{ $.Values.namespace }}
roleRef:
  kind: Role
  name: ecr-secret-manager
  apiGroup: rbac.authorization.k8s.io
{{- end }}