{{- range .Values.targetNamespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $.Release.Name }}
  namespace: {{ . }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["{{ $.Values.secretName }}"]
    verbs: ["get", "update", "patch"]
{{- if $.Values.serviceAccount.patchDefault }}
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get", "patch"]
    resourceNames: ["{{ $.Values.serviceAccount.name }}"]
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $.Release.Name }}
  namespace: {{ . }}
subjects:
  - kind: ServiceAccount
    name: {{ $.Release.Name }}
    namespace: {{ $.Values.namespace }}
roleRef:
  kind: Role
  name: {{ $.Release.Name }}
  apiGroup: rbac.authorization.k8s.io
{{- if $.Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.serviceAccount.name }}
  namespace: {{ . }}
{{- end }}
{{- end }}